config/routes.rb
Rails.application.routes.draw do
  resources :forecast_logs

  resources :forecast_providers

  resources :station_logs

  resources :stations

  get 'welcome/index'

  root 'welcome#index'

end

app/models/forecast_provider.rb
class ForecastProvider < ActiveRecord::Base
  serialize :provides, JSON
  serialize :apiparams, JSON
end

app/controllers/forecast_providers_controller.rb
class ForecastProvidersController < ApplicationController
  before_action :set_forecast_provider, only: [:show, :edit, :update, :destroy]

  # GET /forecast_providers
  # GET /forecast_providers.json
  def index
    @forecast_providers = ForecastProvider.all
  end

  # GET /forecast_providers/1
  # GET /forecast_providers/1.json
  def show
  end

  # GET /forecast_providers/new
  def new
    #@forecast_provider = ForecastProvider.new
  end

  # GET /forecast_providers/1/edit
  def edit
  end

  # POST /forecast_providers
  # POST /forecast_providers.json
  def create
    # @forecast_provider = ForecastProvider.new(forecast_provider_params)
    #
    # respond_to do |format|
    #   if @forecast_provider.save
    #     format.html { redirect_to @forecast_provider, notice: 'Forecast provider was successfully created.' }
    #     format.json { render :show, status: :created, location: @forecast_provider }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @forecast_provider.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /forecast_providers/1
  # PATCH/PUT /forecast_providers/1.json
  def update
    # respond_to do |format|
    #   if @forecast_provider.update(forecast_provider_params)
    #     format.html { redirect_to @forecast_provider, notice: 'Forecast provider was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @forecast_provider }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @forecast_provider.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /forecast_providers/1
  # DELETE /forecast_providers/1.json
  def destroy
    # @forecast_provider.destroy
    # respond_to do |format|
    #   format.html { redirect_to forecast_providers_url, notice: 'Forecast provider was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forecast_provider
      @forecast_provider = ForecastProvider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forecast_provider_params
      params.require(:forecast_provider).permit(:name, :apitype, :apiparams, :provides)
    end
end

app/helpers/forecast_providers_helper.rb
module ForecastProvidersHelper
end

app/views/forecast_providers/_form.html.erb
<%= form_for(@forecast_provider) do |f| %>
  <% if @forecast_provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forecast_provider.errors.count, "error") %> prohibited this forecast_provider from being saved:</h2>

      <ul>
      <% @forecast_provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :apitype %><br>
    <%= f.text_field :apitype %>
  </div>
  <div class="field">
    <%= f.label :apiparams %><br>
    <%= f.text_area :apiparams %>
  </div>
  <div class="field">
    <%= f.label :provides %><br>
    <%= f.text_area :provides %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forecast_providers/edit.html.erb
<h1>Editing Forecast Provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @forecast_provider %> |
<%= link_to 'Back', forecast_providers_path %>

app/views/forecast_providers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Forecast Providers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Apitype</th>
      <th>Apiparams</th>
      <th>Provides</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forecast_providers.each do |forecast_provider| %>
      <tr>
        <td><%= forecast_provider.name %></td>
        <td><%= forecast_provider.apitype %></td>
        <td><%= forecast_provider.apiparams %></td>
        <td><%= forecast_provider.provides %></td>
        <td><%= link_to 'Show', forecast_provider %></td>
        <td><%= link_to 'Edit', edit_forecast_provider_path(forecast_provider) %></td>
        <td><%= link_to 'Destroy', forecast_provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forecast provider', new_forecast_provider_path %>

app/views/forecast_providers/new.html.erb
<h1>New Forecast Provider</h1>

<%= render 'form' %>

<%= link_to 'Back', forecast_providers_path %>

app/views/forecast_providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @forecast_provider.name %>
</p>

<p>
  <strong>Apitype:</strong>
  <%= @forecast_provider.apitype %>
</p>

<p>
  <strong>Apiparams:</strong>
  <%= @forecast_provider.apiparams %>
</p>

<p>
  <strong>Provides:</strong>
  <%= @forecast_provider.provides %>
</p>

<%= link_to 'Edit', edit_forecast_provider_path(@forecast_provider) %> |
<%= link_to 'Back', forecast_providers_path %>