config/routes.rb
Rails.application.routes.draw do
  resources :forecast_logs

  resources :forecast_providers

  resources :station_logs

  resources :stations

  get 'welcome/index'

  root 'welcome#index'

end

app/models/station.rb
class Station < ActiveRecord::Base
  serialize :provides, JSON
  serialize :apiparams, JSON
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    # @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    # @station = Station.new(station_params)
    #
    # respond_to do |format|
    #   if @station.save
    #     format.html { redirect_to @station, notice: 'Station was successfully created.' }
    #     format.json { render :show, status: :created, location: @station }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @station.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    # respond_to do |format|
    #   if @station.update(station_params)
    #     format.html { redirect_to @station, notice: 'Station was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @station }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @station.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    # @station.destroy
    # respond_to do |format|
    #   format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name, :lat, :lon, :apitype, :apiparams, :provides)
    end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.label :apitype %><br>
    <%= f.text_field :apitype %>
  </div>
  <div class="field">
    <%= f.label :apiparams %><br>
    <%= f.text_area :apiparams %>
  </div>
  <div class="field">
    <%= f.label :provides %><br>
    <%= f.text_area :provides %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form' %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Apitype</th>
      <th>Apiparams</th>
      <th>Provides</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.name %></td>
        <td><%= station.lat %></td>
        <td><%= station.lon %></td>
        <td><%= station.apitype %></td>
        <td><%= station.apiparams %></td>
        <td><%= station.provides %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form' %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @station.name %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @station.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @station.lon %>
</p>

<p>
  <strong>Apitype:</strong>
  <%= @station.apitype %>
</p>

<p>
  <strong>Apiparams:</strong>
  <%= @station.apiparams %>
</p>

<p>
  <strong>Provides:</strong>
  <%= @station.provides %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>