config/routes.rb
Rails.application.routes.draw do
  resources :forecast_logs

  resources :forecast_providers

  resources :station_logs

  resources :stations

  get 'welcome/index'

  root 'welcome#index'

end

app/models/station_log.rb
class StationLog < ActiveRecord::Base
  belongs_to :station

  default_scope { where(normalized_timestamp: (7.day.ago.to_date..Time.now)).order(normalized_timestamp: :asc, station_id: :asc) }
end

app/controllers/station_logs_controller.rb
class StationLogsController < ApplicationController
  before_action :set_station_log, only: [:show, :edit, :update, :destroy]

  # GET /station_logs
  # GET /station_logs.json
  def index
    @station_logs = StationLog.all
  end

  # GET /station_logs/1
  # GET /station_logs/1.json
  def show
  end

  # GET /station_logs/new
  def new
    #@station_log = StationLog.new
  end

  # GET /station_logs/1/edit
  def edit
  end

  # POST /station_logs
  # POST /station_logs.json
  def create
    # @station_log = StationLog.new(station_log_params)
    #
    # respond_to do |format|
    #   if @station_log.save
    #     format.html { redirect_to @station_log, notice: 'Station log was successfully created.' }
    #     format.json { render :show, status: :created, location: @station_log }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @station_log.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /station_logs/1
  # PATCH/PUT /station_logs/1.json
  def update
    # respond_to do |format|
    #   if @station_log.update(station_log_params)
    #     format.html { redirect_to @station_log, notice: 'Station log was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @station_log }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @station_log.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /station_logs/1
  # DELETE /station_logs/1.json
  def destroy
    # @station_log.destroy
    # respond_to do |format|
    #   format.html { redirect_to station_logs_url, notice: 'Station log was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station_log
      @station_log = StationLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_log_params
      params.require(:station_log).permit(:station_id, :normalized_timestamp, :pressure, :windspeed, :winddirection, :humidity, :dewpoint, :precipitation)
    end
end

app/helpers/station_logs_helper.rb
module StationLogsHelper
end

app/views/station_logs/_form.html.erb
<%= form_for(@station_log) do |f| %>
  <% if @station_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station_log.errors.count, "error") %> prohibited this station_log from being saved:</h2>

      <ul>
      <% @station_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :station_id %><br>
    <%= f.text_field :station_id %>
  </div>
  <div class="field">
    <%= f.label :normalized_timestamp %><br>
    <%= f.datetime_select :normalized_timestamp %>
  </div>
  <div class="field">
    <%= f.label :pressure %><br>
    <%= f.text_field :pressure %>
  </div>
  <div class="field">
    <%= f.label :windspeed %><br>
    <%= f.number_field :windspeed %>
  </div>
  <div class="field">
    <%= f.label :winddirection %><br>
    <%= f.text_field :winddirection %>
  </div>
  <div class="field">
    <%= f.label :humidity %><br>
    <%= f.text_field :humidity %>
  </div>
  <div class="field">
    <%= f.label :dewpoint %><br>
    <%= f.text_field :dewpoint %>
  </div>
  <div class="field">
    <%= f.label :precipitation %><br>
    <%= f.text_field :precipitation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/station_logs/edit.html.erb
<h1>Editing Station Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @station_log %> |
<%= link_to 'Back', station_logs_path %>

app/views/station_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Station Logs</h1>

<table>
  <thead>
    <tr>
      <th>Station</th>
      <th>Normalized timestamp</th>
      <th>Pressure</th>
      <th>Windspeed</th>
      <th>Winddirection</th>
      <th>Humidity</th>
      <th>Dewpoint</th>
      <th>Precipitation</th>
      <th>Temperature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @station_logs.each do |station_log| %>
      <tr>
        <td><%= station_log.station.name %></td>
        <td><%= station_log.normalized_timestamp %></td>
        <td><%= station_log.pressure %></td>
        <td><%= station_log.windspeed %></td>
        <td><%= station_log.winddirection %></td>
        <td><%= station_log.humidity %></td>
        <td><%= station_log.dewpoint %></td>
        <td><%= station_log.precipitation %></td>
        <td><%= station_log.temperature %></td>
        <td><%= link_to 'Show', station_log %></td>
        <td><%= link_to 'Edit', edit_station_log_path(station_log) %></td>
        <td><%= link_to 'Destroy', station_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station log', new_station_log_path %>

app/views/station_logs/new.html.erb
<h1>New Station Log</h1>

<%= render 'form' %>

<%= link_to 'Back', station_logs_path %>

app/views/station_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Station:</strong>
  <%= @station_log.station.name %>
</p>

<p>
  <strong>Normalized timestamp:</strong>
  <%= @station_log.normalized_timestamp %>
</p>

<p>
  <strong>Pressure:</strong>
  <%= @station_log.pressure %>
</p>

<p>
  <strong>Windspeed:</strong>
  <%= @station_log.windspeed %>
</p>

<p>
  <strong>Winddirection:</strong>
  <%= @station_log.winddirection %>
</p>

<p>
  <strong>Humidity:</strong>
  <%= @station_log.humidity %>
</p>

<p>
  <strong>Dewpoint:</strong>
  <%= @station_log.dewpoint %>
</p>

<p>
  <strong>Precipitation:</strong>
  <%= @station_log.precipitation %>
</p>

<%= link_to 'Edit', edit_station_log_path(@station_log) %> |
<%= link_to 'Back', station_logs_path %>