config/routes.rb
Rails.application.routes.draw do
  resources :forecast_logs

  resources :forecast_providers

  resources :station_logs

  resources :stations

  get 'welcome/index'

  root 'welcome#index'

end

app/models/forecast_log.rb
class ForecastLog < ActiveRecord::Base
  belongs_to :forecast_provider

  default_scope { where(day: (7.day.ago.to_date..Date.today)).order(day: :asc) }

  def day
    self[:day].to_date
  end
end

app/controllers/forecast_logs_controller.rb
class ForecastLogsController < ApplicationController
  before_action :set_forecast_log, only: [:show, :edit, :update, :destroy]

  # GET /forecast_logs
  # GET /forecast_logs.json
  def index
    @forecast_logs = ForecastLog.all
  end

  # GET /forecast_logs/1
  # GET /forecast_logs/1.json
  def show
  end

  # GET /forecast_logs/new
  def new
    puts "Disabled"
    #@forecast_log = ForecastLog.new
  end

  # GET /forecast_logs/1/edit
  def edit
  end

  # POST /forecast_logs
  # POST /forecast_logs.json
  def create
    puts "Disabled"
    #
    # @forecast_log = ForecastLog.new(forecast_log_params)
    #
    # respond_to do |format|
    #   if @forecast_log.save
    #     format.html { redirect_to @forecast_log, notice: 'Forecast log was successfully created.' }
    #     format.json { render :show, status: :created, location: @forecast_log }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @forecast_log.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /forecast_logs/1
  # PATCH/PUT /forecast_logs/1.json
  def update
    # respond_to do |format|
    #   if @forecast_log.update(forecast_log_params)
    #     format.html { redirect_to @forecast_log, notice: 'Forecast log was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @forecast_log }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @forecast_log.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /forecast_logs/1
  # DELETE /forecast_logs/1.json
  def destroy
    # @forecast_log.destroy
    # respond_to do |format|
    #   format.html { redirect_to forecast_logs_url, notice: 'Forecast log was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forecast_log
      @forecast_log = ForecastLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forecast_log_params
      params.require(:forecast_log).permit(:forecast_provider_id, :day, :temperature_max, :temperature_min, :precipitation, :pressure)
    end
end

app/helpers/forecast_logs_helper.rb
module ForecastLogsHelper
end

app/views/forecast_logs/_form.html.erb
<%= form_for(@forecast_log) do |f| %>
  <% if @forecast_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forecast_log.errors.count, "error") %> prohibited this forecast_log from being saved:</h2>

      <ul>
      <% @forecast_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :forecast_provider_id %><br>
    <%= f.text_field :forecast_provider_id %>
  </div>
  <div class="field">
    <%= f.label :day %><br>
    <%= f.datetime_select :day %>
  </div>
  <div class="field">
    <%= f.label :temperature_max %><br>
    <%= f.text_field :temperature_max %>
  </div>
  <div class="field">
    <%= f.label :temperature_min %><br>
    <%= f.text_field :temperature_min %>
  </div>
  <div class="field">
    <%= f.label :precipitation %><br>
    <%= f.text_field :precipitation %>
  </div>
  <div class="field">
    <%= f.label :pressure %><br>
    <%= f.text_field :pressure %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forecast_logs/edit.html.erb
<h1>Editing Forecast Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @forecast_log %> |
<%= link_to 'Back', forecast_logs_path %>

app/views/forecast_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Forecast Logs</h1>

<table>
  <thead>
    <tr>
      <th>Forecast provider</th>
      <th>Day</th>
      <th>Temperature max</th>
      <th>Temperature min</th>
      <th>Precipitation</th>
      <th>Pressure</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forecast_logs.each do |forecast_log| %>
      <tr>
        <td><%= forecast_log.forecast_provider %></td>
        <td><%= forecast_log.day %></td>
        <td><%= forecast_log.temperature_max %></td>
        <td><%= forecast_log.temperature_min %></td>
        <td><%= forecast_log.precipitation %></td>
        <td><%= forecast_log.pressure %></td>
        <td><%= link_to 'Show', forecast_log %></td>
        <td><%= link_to 'Edit', edit_forecast_log_path(forecast_log) %></td>
        <td><%= link_to 'Destroy', forecast_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forecast log', new_forecast_log_path %>

app/views/forecast_logs/new.html.erb
<h1>New Forecast Log</h1>

<%= render 'form' %>

<%= link_to 'Back', forecast_logs_path %>

app/views/forecast_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Forecast provider:</strong>
  <%= @forecast_log.forecast_provider %>
</p>

<p>
  <strong>Day:</strong>
  <%= @forecast_log.day %>
</p>

<p>
  <strong>Temperature max:</strong>
  <%= @forecast_log.temperature_max %>
</p>

<p>
  <strong>Temperature min:</strong>
  <%= @forecast_log.temperature_min %>
</p>

<p>
  <strong>Precipitation:</strong>
  <%= @forecast_log.precipitation %>
</p>

<p>
  <strong>Pressure:</strong>
  <%= @forecast_log.pressure %>
</p>

<%= link_to 'Edit', edit_forecast_log_path(@forecast_log) %> |
<%= link_to 'Back', forecast_logs_path %>